//! `McpHandler` — the `rmcp` `ServerHandler` implementation for localdb.
//!
//! Tool routing (`tools/list`, `tools/call`) is entirely macro-generated by
//! `#[tool_router]`/`#[tool_handler]`; there is no hand-written dispatch
//! table. Each `#[tool]` method here resolves the caller's `Principal`
//! (see below), resolves the current store list via `self.provider`
//! (realtime — see `store_provider.rs`), and then forwards to a `tools::*`
//! fn — all validation and business logic lives in `tools.rs`, which keeps
//! its pure `&[AvailableStore]` signatures unchanged.
//!
//! ## Principal resolution (specs/05-surfaces.md §4, T3)
//!
//! On the HTTP transport, rmcp's `StreamableHttpService` injects the
//! request's remaining `http::request::Parts` into the tool call's
//! `RequestContext.extensions`; `Parts.extensions` in turn carries whatever
//! the daemon's axum `require_auth` middleware inserted — including the
//! authenticated `Principal`. `default_principal` covers the transports
//! with no HTTP request at all:
//!
//! - embedded stdio (`localdb mcp`, no daemon): `Some(local_trust)` — the
//!   caller is already trusted as local-files-equivalent (D8);
//! - daemon in open mode: `Some(local_trust)` (the middleware inserts it on
//!   each request anyway; the default keeps construction uniform);
//! - daemon with auth **enforced**: `None`, so a missing request-extension
//!   `Principal` is an authentication error (fail closed) — never full
//!   access.
//!
//! T5: admins (and `local_trust`) see every store; `member` principals are
//! no longer rejected wholesale — instead the resolved store list is
//! filtered per call to just the `shared` stores they hold a grant for
//! (D7, D12), via `Principal::can_read_store`.
//!
//! specs/05-surfaces.md §3.1: a store name a tool call explicitly asks for
//! (`search`'s `stores` filter) that exists but was filtered out by D7 is a
//! `forbidden` tool error, not `store_not_found` — matching the HTTP surface
//! (`server::search_service::SearchService::query`'s `store_filter` handling)
//! exactly. Only a name absent from the *full*, pre-filter store list stays
//! `store_not_found`. With no store named explicitly (unfiltered `search`,
//! or `list_stores`), the visible set is silently narrowed as before — there
//! is nothing to be "forbidden" from since nothing specific was requested.

use std::sync::Arc;

use rmcp::{
    handler::server::{router::tool::ToolRouter, wrapper::Parameters},
    model::{CallToolResult, Extensions, Implementation, ServerCapabilities, ServerInfo},
    service::RequestContext,
    tool, tool_handler, tool_router, RoleServer, ServerHandler,
};

use localdb_core::{auth::Principal, types::StoreVisibility, Embedder, Error};

use crate::args::{GetChunksArgs, GetDocumentArgs, SearchArgs};
use crate::store_provider::StoreProvider;
use crate::tools::{self, AvailableStore};

/// Convert a `StoreProvider::available_stores` failure into a tool-level MCP
/// error result, so a broken/unavailable store backend surfaces as a normal
/// `CallToolResult { is_error: Some(true), .. }` rather than a panic — the
/// service itself stays up and can serve the next call.
fn provider_error(e: &Error) -> CallToolResult {
    tools::typed_error(e.code(), format!("failed to resolve available stores: {e}"))
}

/// Embedded-stdio / HTTP MCP server handler: holds a `StoreProvider` (stores
/// are resolved fresh on every tool call, not snapshotted at construction —
/// see `store_provider.rs`), the embedder used for `search`, whether
/// `--allow-write` was passed (parsed but always rejected in v1 — no
/// mutating tool is registered), and the fallback `Principal` for
/// transports that carry no per-request identity (see the module doc).
#[derive(Clone)]
pub struct McpHandler {
    pub provider: Arc<dyn StoreProvider>,
    pub embedder: Arc<dyn Embedder>,
    pub allow_write: bool,
    default_principal: Option<Principal>,
    tool_router: ToolRouter<Self>,
}

impl McpHandler {
    /// Create a new handler over the given store provider and embedder.
    ///
    /// `default_principal` is used when the request context carries no
    /// `Principal` (see the module doc): pass `Some(Principal::local_trust())`
    /// for embedded stdio and open-mode daemons, `None` when the daemon
    /// enforces auth so a missing principal fails closed.
    pub fn new(
        provider: Arc<dyn StoreProvider>,
        embedder: Arc<dyn Embedder>,
        allow_write: bool,
        default_principal: Option<Principal>,
    ) -> Self {
        Self {
            provider,
            embedder,
            allow_write,
            default_principal,
            tool_router: Self::tool_router(),
        }
    }

    /// Resolve the caller's `Principal` for this tool call (R4).
    ///
    /// Takes the call's `rmcp::model::Extensions` (from
    /// `RequestContext.extensions`) rather than the whole context so the
    /// resolution path is unit-testable — `RequestContext` cannot be
    /// constructed outside rmcp (its `Peer::new` is `pub(crate)`), but
    /// `Extensions` can.
    ///
    /// Priority:
    /// 1. A `Principal` in the HTTP request extensions, reached through the
    ///    `http::request::Parts` rmcp injects into
    ///    `RequestContext.extensions` on the Streamable HTTP transport —
    ///    this is what the daemon's `require_auth` middleware inserted.
    /// 2. A `Principal` directly in the rmcp extensions (not produced by
    ///    any current transport; checked for completeness).
    /// 3. `self.default_principal` (embedded stdio / open mode).
    /// 4. Otherwise: fail closed with an `unauthorized` tool error — on an
    ///    enforced-auth daemon a missing extension means the auth layer was
    ///    bypassed, and answering with full access would be privilege
    ///    escalation.
    fn principal_for(&self, extensions: &Extensions) -> Result<Principal, CallToolResult> {
        if let Some(parts) = extensions.get::<http::request::Parts>() {
            if let Some(principal) = parts.extensions.get::<Principal>() {
                return Ok(principal.clone());
            }
        }
        if let Some(principal) = extensions.get::<Principal>() {
            return Ok(principal.clone());
        }
        match &self.default_principal {
            Some(principal) => Ok(principal.clone()),
            None => Err(tools::typed_error(
                "unauthorized",
                "no authenticated principal on this request; the MCP endpoint requires a \
                 valid bearer token",
            )),
        }
    }

    /// Resolve the current store list, or `None` (having already produced
    /// the tool-error result) on provider failure.
    async fn resolve_stores(&self) -> Result<Vec<AvailableStore>, CallToolResult> {
        self.provider
            .available_stores()
            .await
            .map_err(|e| provider_error(&e))
    }

    /// D7 filtering: keep only the stores `principal` may read. Admins (and
    /// `local_trust`) keep every store; members keep only `shared` stores
    /// they hold a grant for. An unrecognized visibility string (never
    /// produced by any current `StoreProvider`, so only reachable via a bug)
    /// is treated as `private` — fail safe, deny by default, rather than
    /// leak an unknown-shaped store to a member.
    fn filter_visible(principal: &Principal, stores: &[AvailableStore]) -> Vec<AvailableStore> {
        stores
            .iter()
            .filter(|s| {
                let visibility = StoreVisibility::parse(&s.descriptor.visibility)
                    .unwrap_or(StoreVisibility::Private);
                principal.can_read_store(&s.descriptor.name, visibility)
            })
            .cloned()
            .collect()
    }

    /// Shared per-tool preamble: resolve the caller's principal (fail closed
    /// if none — see `principal_for`), resolve the live store list, then
    /// filter it to what that principal may read (D7). Tools thus never see
    /// a store the caller isn't entitled to. For tools with no explicit
    /// store-name argument (`get_document`/`get_chunks`/`list_stores`) an
    /// invisible store behaves identically to an unknown one — there's
    /// nothing named to be "forbidden" from. `search`'s `stores` filter is
    /// the one call site with an explicit name, so it uses
    /// `authorize_and_resolve_with_full` instead (see below).
    async fn authorize_and_resolve(
        &self,
        extensions: &Extensions,
    ) -> Result<Vec<AvailableStore>, CallToolResult> {
        let principal = self.principal_for(extensions)?;
        let stores = self.resolve_stores().await?;
        Ok(Self::filter_visible(&principal, &stores))
    }

    /// Like `authorize_and_resolve`, but also returns the full, pre-D7-filter
    /// store list alongside the visible one — needed by `search_inner` to
    /// distinguish a named store that's unreadable (present in `full`,
    /// dropped from the visible set) from one that's genuinely unknown
    /// (absent from `full` too); see `forbidden_for_named_unreadable_store`.
    async fn authorize_and_resolve_with_full(
        &self,
        extensions: &Extensions,
    ) -> Result<(Vec<AvailableStore>, Vec<AvailableStore>), CallToolResult> {
        let principal = self.principal_for(extensions)?;
        let stores = self.resolve_stores().await?;
        let visible = Self::filter_visible(&principal, &stores);
        Ok((stores, visible))
    }

    /// specs/05-surfaces.md §3.1: a store name in `requested` that exists in
    /// `full` (the unfiltered store list) but was dropped from `visible` by
    /// D7 filtering is `forbidden`, not `store_not_found` — the caller named
    /// a real store and was refused, mirroring the HTTP surface's
    /// `server::search_service::SearchService::query` (`store_filter` naming
    /// an ungranted store -> 403). A name absent from `full` returns `None`
    /// here and falls through unchanged to the tool's own `store_not_found`
    /// handling (it only ever sees `visible`, so it's not found there
    /// either). Returns the *first* unreadable name found, matching the HTTP
    /// surface's fail-fast-on-first-bad-name behavior.
    fn forbidden_for_named_unreadable_store(
        full: &[AvailableStore],
        visible: &[AvailableStore],
        requested: &[String],
    ) -> Option<CallToolResult> {
        for name in requested {
            let exists = full.iter().any(|s| &s.descriptor.name == name);
            let is_visible = visible.iter().any(|s| &s.descriptor.name == name);
            if exists && !is_visible {
                return Some(tools::typed_error(
                    "forbidden",
                    format!("you do not have access to store '{name}'"),
                ));
            }
        }
        None
    }

    // The `*_inner` methods below carry the full tool behavior against a
    // bare `Extensions`; the `#[tool]` wrappers only peel it off the
    // `RequestContext`. Unit tests drive the inner methods directly
    // (`RequestContext` is not constructible outside rmcp); the
    // wrapper→inner hop plus rmcp's own extension propagation is covered by
    // the end-to-end test in `server/tests/` (R4).

    async fn search_inner(&self, args: SearchArgs, extensions: &Extensions) -> CallToolResult {
        let (full, visible) = match self.authorize_and_resolve_with_full(extensions).await {
            Ok(s) => s,
            Err(result) => return result,
        };
        if let Some(names) = &args.stores {
            if let Some(result) = Self::forbidden_for_named_unreadable_store(&full, &visible, names)
            {
                return result;
            }
        }
        tools::tool_search(&visible, self.embedder.as_ref(), args).await
    }

    async fn get_document_inner(
        &self,
        args: GetDocumentArgs,
        extensions: &Extensions,
    ) -> CallToolResult {
        let stores = match self.authorize_and_resolve(extensions).await {
            Ok(s) => s,
            Err(result) => return result,
        };
        tools::tool_get_document(&stores, args).await
    }

    async fn get_chunks_inner(
        &self,
        args: GetChunksArgs,
        extensions: &Extensions,
    ) -> CallToolResult {
        let stores = match self.authorize_and_resolve(extensions).await {
            Ok(s) => s,
            Err(result) => return result,
        };
        tools::tool_get_chunks(&stores, args).await
    }

    async fn list_stores_inner(&self, extensions: &Extensions) -> CallToolResult {
        let stores = match self.authorize_and_resolve(extensions).await {
            Ok(s) => s,
            Err(result) => return result,
        };
        tools::tool_list_stores(&stores).await
    }
}

#[tool_router]
impl McpHandler {
    /// Hybrid search (BM25 + dense vector) across indexed stores. Returns a
    /// ranked list of citations in the canonical localdb Citation JSON shape.
    #[tool(
        description = "Hybrid search (BM25 + dense vector) across indexed stores. Returns a ranked list of citations in the canonical localdb Citation JSON shape."
    )]
    async fn search(
        &self,
        Parameters(args): Parameters<SearchArgs>,
        ctx: RequestContext<RoleServer>,
    ) -> CallToolResult {
        self.search_inner(args, &ctx.extensions).await
    }

    /// Fetch the normalized text and metadata for a document by its ID.
    #[tool(description = "Fetch the normalized text and metadata for a document by its ID or URI.")]
    async fn get_document(
        &self,
        Parameters(args): Parameters<GetDocumentArgs>,
        ctx: RequestContext<RoleServer>,
    ) -> CallToolResult {
        self.get_document_inner(args, &ctx.extensions).await
    }

    /// Fetch a document's chunks in order, paginated by offset/limit.
    #[tool(
        description = "Fetch a document's chunks in order (block_seq, seq_in_block), paginated by offset/limit."
    )]
    async fn get_chunks(
        &self,
        Parameters(args): Parameters<GetChunksArgs>,
        ctx: RequestContext<RoleServer>,
    ) -> CallToolResult {
        self.get_chunks_inner(args, &ctx.extensions).await
    }

    /// List all available stores with their names, visibility, and
    /// document/chunk counts.
    #[tool(
        description = "List all available stores with their names, visibility, and document/chunk counts."
    )]
    async fn list_stores(&self, ctx: RequestContext<RoleServer>) -> CallToolResult {
        self.list_stores_inner(&ctx.extensions).await
    }
}

// `router = self.tool_router` reuses the stored instance field rather than
// rebuilding a fresh router via `Self::tool_router()` on every call (rmcp's
// default when no `router = ...` is given) — the field would otherwise be
// dead weight per rustc's dead-code lint, and reconstructing it per-call is
// wasted work for a routing table that never changes at runtime.
#[tool_handler(router = self.tool_router)]
impl ServerHandler for McpHandler {
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(ServerCapabilities::builder().enable_tools().build())
            .with_server_info(Implementation::new("localdb", env!("CARGO_PKG_VERSION")))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::store_provider::StaticStoreProvider;
    use async_trait::async_trait;
    use localdb_core::auth::{Role, StoreAccess};
    use localdb_core::embedder::FakeEmbedder;

    /// A `StoreProvider` that always fails, to prove a provider error
    /// surfaces as a tool-level MCP error (not a panic) and the handler
    /// remains usable afterward.
    struct ErrorStoreProvider;

    #[async_trait]
    impl StoreProvider for ErrorStoreProvider {
        async fn available_stores(&self) -> Result<Vec<AvailableStore>, Error> {
            Err(Error::Internal {
                message: "backend unavailable".to_string(),
                correlation_id: "test_provider_error".to_string(),
            })
        }
    }

    fn embedder() -> Arc<dyn Embedder> {
        Arc::new(FakeEmbedder::new(4))
    }

    /// Empty rmcp extensions — what an embedded stdio call looks like (no
    /// HTTP `Parts`, no injected `Principal`).
    fn no_extensions() -> Extensions {
        Extensions::default()
    }

    /// Extensions carrying `principal` the way the daemon's HTTP path does:
    /// inside the request extensions of the `http::request::Parts` rmcp
    /// injects into `RequestContext.extensions`.
    fn http_extensions_with_principal(principal: Principal) -> Extensions {
        let mut extensions = Extensions::default();
        let (mut parts, _body) = http::Request::new(()).into_parts();
        parts.extensions.insert(principal);
        extensions.insert(parts);
        extensions
    }

    fn member(name: &str) -> Principal {
        Principal {
            user_id: format!("uid-{name}"),
            name: name.to_string(),
            role: Role::Member,
            access: StoreAccess::Granted(Default::default()),
        }
    }

    fn error_code(result: &CallToolResult) -> String {
        let text = result.content[0].as_text().unwrap().text.clone();
        let parsed: serde_json::Value = serde_json::from_str(&text).expect("must be JSON");
        parsed["error"]["code"].as_str().unwrap().to_string()
    }

    #[tokio::test]
    async fn list_stores_returns_tool_error_when_provider_fails() {
        let handler = McpHandler::new(
            Arc::new(ErrorStoreProvider),
            embedder(),
            false,
            Some(Principal::local_trust()),
        );
        let result = handler.list_stores_inner(&no_extensions()).await;
        assert_eq!(result.is_error, Some(true));
        let text = result.content[0].as_text().unwrap().text.clone();
        let parsed: serde_json::Value = serde_json::from_str(&text).expect("must be JSON");
        assert_eq!(parsed["error"]["code"].as_str().unwrap(), "internal");
        assert!(parsed["error"]["message"]
            .as_str()
            .unwrap()
            .contains("backend unavailable"));
    }

    #[tokio::test]
    async fn handler_stays_usable_after_a_provider_error() {
        let handler = McpHandler::new(
            Arc::new(ErrorStoreProvider),
            embedder(),
            false,
            Some(Principal::local_trust()),
        );

        let first = handler.list_stores_inner(&no_extensions()).await;
        assert_eq!(first.is_error, Some(true));

        // The service must not have panicked or otherwise become unusable —
        // a second call against the same (still-failing) provider still
        // produces a clean tool-level error, not a crash.
        let second = handler.list_stores_inner(&no_extensions()).await;
        assert_eq!(second.is_error, Some(true));
    }

    #[tokio::test]
    async fn list_stores_succeeds_once_provider_recovers() {
        // Same handler *shape* as the static case — proves a working
        // provider still round-trips normally through `resolve_stores`.
        let provider = Arc::new(StaticStoreProvider::new(vec![]));
        let handler = McpHandler::new(provider, embedder(), false, Some(Principal::local_trust()));
        let result = handler.list_stores_inner(&no_extensions()).await;
        assert_ne!(result.is_error, Some(true));
    }

    // --- Principal resolution (R4, fail-closed) ---

    #[tokio::test]
    async fn no_principal_and_no_default_fails_closed() {
        // Enforced-HTTP construction: default_principal = None. A context
        // with no injected Principal must produce an unauthorized tool
        // error — never full access.
        let provider = Arc::new(StaticStoreProvider::new(vec![]));
        let handler = McpHandler::new(provider, embedder(), false, None);
        let result = handler.list_stores_inner(&no_extensions()).await;
        assert_eq!(result.is_error, Some(true));
        assert_eq!(error_code(&result), "unauthorized");
    }

    #[tokio::test]
    async fn http_injected_admin_principal_is_used() {
        // Even with no default (enforced mode), a Principal delivered via
        // http::request::Parts extensions authorizes the call.
        let provider = Arc::new(StaticStoreProvider::new(vec![]));
        let handler = McpHandler::new(provider, embedder(), false, None);
        let result = handler
            .list_stores_inner(&http_extensions_with_principal(Principal::local_trust()))
            .await;
        assert_ne!(result.is_error, Some(true));
    }

    #[tokio::test]
    async fn member_principal_is_no_longer_rejected_wholesale() {
        // T5 lifts the T3 interim member-403 block: a member now passes
        // (against an empty store set the call trivially succeeds with no
        // stores, rather than erroring).
        let provider = Arc::new(StaticStoreProvider::new(vec![]));
        let handler = McpHandler::new(provider, embedder(), false, None);
        let result = handler
            .list_stores_inner(&http_extensions_with_principal(member("bob")))
            .await;
        assert_ne!(result.is_error, Some(true));
    }

    #[tokio::test]
    async fn default_local_trust_authorizes_embedded_calls() {
        // Embedded stdio: no HTTP Parts at all; default local_trust applies.
        let provider = Arc::new(StaticStoreProvider::new(vec![]));
        let handler = McpHandler::new(provider, embedder(), false, Some(Principal::local_trust()));
        let result = handler.list_stores_inner(&no_extensions()).await;
        assert_ne!(result.is_error, Some(true));
    }

    #[tokio::test]
    async fn member_default_principal_is_no_longer_gated_either() {
        // Nothing constructs this today, but the lifted gate must hold no
        // matter how the principal arrived.
        let provider = Arc::new(StaticStoreProvider::new(vec![]));
        let handler = McpHandler::new(provider, embedder(), false, Some(member("carol")));
        let result = handler.list_stores_inner(&no_extensions()).await;
        assert_ne!(result.is_error, Some(true));
    }

    // -----------------------------------------------------------------
    // T5: D7 store filtering by principal
    // -----------------------------------------------------------------

    fn store_with_visibility(name: &str, visibility: &str) -> AvailableStore {
        AvailableStore::new(
            crate::tools::StoreDescriptor {
                id: format!("id-{name}"),
                name: name.to_string(),
                visibility: visibility.to_string(),
            },
            Box::new(localdb_core::store::FakeStore::new()),
        )
    }

    fn stores_json(result: &CallToolResult) -> Vec<String> {
        let text = result.content[0].as_text().unwrap().text.clone();
        let parsed: serde_json::Value = serde_json::from_str(&text).unwrap();
        parsed["stores"]
            .as_array()
            .unwrap()
            .iter()
            .map(|s| s["name"].as_str().unwrap().to_string())
            .collect()
    }

    #[tokio::test]
    async fn admin_sees_every_store_private_and_shared() {
        let provider = Arc::new(StaticStoreProvider::new(vec![
            store_with_visibility("shared-docs", "shared"),
            store_with_visibility("secret-docs", "private"),
        ]));
        let handler = McpHandler::new(provider, embedder(), false, None);
        let result = handler
            .list_stores_inner(&http_extensions_with_principal(Principal::local_trust()))
            .await;
        assert_ne!(result.is_error, Some(true));
        let mut names = stores_json(&result);
        names.sort();
        assert_eq!(names, vec!["secret-docs", "shared-docs"]);
    }

    #[tokio::test]
    async fn member_sees_only_granted_shared_stores() {
        let provider = Arc::new(StaticStoreProvider::new(vec![
            store_with_visibility("granted-shared", "shared"),
            store_with_visibility("ungranted-shared", "shared"),
            store_with_visibility("secret-private", "private"),
        ]));
        let handler = McpHandler::new(provider, embedder(), false, None);
        let principal = Principal {
            user_id: "u1".into(),
            name: "member-with-grant".into(),
            role: Role::Member,
            access: StoreAccess::Granted(["granted-shared".to_string()].into_iter().collect()),
        };
        let result = handler
            .list_stores_inner(&http_extensions_with_principal(principal))
            .await;
        assert_ne!(result.is_error, Some(true));
        let names = stores_json(&result);
        assert_eq!(names, vec!["granted-shared"]);
    }

    #[tokio::test]
    async fn member_search_naming_an_ungranted_store_is_forbidden_not_not_found() {
        // specs/05-surfaces.md §3.1: a store the member holds no grant for,
        // but that genuinely exists, must be `forbidden` (403 on the HTTP
        // surface) — not collapsed into `store_not_found`, which would be
        // inconsistent with `server::search_service::SearchService::query`'s
        // identical `store_filter` check.
        let provider = Arc::new(StaticStoreProvider::new(vec![store_with_visibility(
            "ungranted",
            "shared",
        )]));
        let handler = McpHandler::new(provider, embedder(), false, None);
        let args = SearchArgs {
            query: "hello".to_string(),
            stores: Some(vec!["ungranted".to_string()]),
            limit: None,
            content_length: None,
        };
        let result = handler
            .search_inner(args, &http_extensions_with_principal(member("dana")))
            .await;
        assert_eq!(result.is_error, Some(true));
        assert_eq!(error_code(&result), "forbidden");
    }

    #[tokio::test]
    async fn member_search_naming_a_truly_unknown_store_is_store_not_found() {
        // A name absent from the full store list entirely (not merely
        // filtered out by D7) must still be `store_not_found` — only
        // "exists but unreadable" is promoted to `forbidden`.
        let provider = Arc::new(StaticStoreProvider::new(vec![store_with_visibility(
            "granted-shared",
            "shared",
        )]));
        let handler = McpHandler::new(provider, embedder(), false, None);
        let principal = Principal {
            user_id: "u1".into(),
            name: "member-with-grant".into(),
            role: Role::Member,
            access: StoreAccess::Granted(["granted-shared".to_string()].into_iter().collect()),
        };
        let args = SearchArgs {
            query: "hello".to_string(),
            stores: Some(vec!["does-not-exist".to_string()]),
            limit: None,
            content_length: None,
        };
        let result = handler
            .search_inner(args, &http_extensions_with_principal(principal))
            .await;
        assert_eq!(result.is_error, Some(true));
        assert_eq!(error_code(&result), "store_not_found");
    }

    #[tokio::test]
    async fn admin_search_naming_any_store_works() {
        // An admin (or local_trust) is never subject to D7 filtering, so
        // naming any real store — private or shared — must succeed.
        let provider = Arc::new(StaticStoreProvider::new(vec![
            store_with_visibility("shared-docs", "shared"),
            store_with_visibility("secret-docs", "private"),
        ]));
        let handler = McpHandler::new(provider, embedder(), false, None);
        let args = SearchArgs {
            query: "hello".to_string(),
            stores: Some(vec!["secret-docs".to_string()]),
            limit: None,
            content_length: None,
        };
        let result = handler
            .search_inner(
                args,
                &http_extensions_with_principal(Principal::local_trust()),
            )
            .await;
        assert_ne!(result.is_error, Some(true));
    }
}
