//! `McpHandler` — the `rmcp` `ServerHandler` implementation for localdb.
//!
//! Tool routing (`tools/list`, `tools/call`) is entirely macro-generated by
//! `#[tool_router]`/`#[tool_handler]`; there is no hand-written dispatch
//! table. Each `#[tool]` method here resolves the caller's `Principal`
//! (see below), resolves the current store list via `self.provider`
//! (realtime — see `store_provider.rs`), and then forwards to a `tools::*`
//! fn — tool validation and retrieval live in `tools`, with document-registry
//! access restricted to the resolved visible stores.
//!
//! ## Principal resolution (specs/05-surfaces.md §4, T3)
//!
//! On the HTTP transport, rmcp's `StreamableHttpService` injects the
//! request's remaining `http::request::Parts` into the tool call's
//! `RequestContext.extensions`; `Parts.extensions` in turn carries whatever
//! the daemon's axum `require_auth` middleware inserted — including the
//! authenticated `Principal`. `default_principal` covers the transports
//! with no HTTP request at all:
//!
//! - embedded stdio (`localdb mcp`, no daemon): `Some(local_trust)` — the
//!   caller is already trusted as local-files-equivalent (D8);
//! - daemon in open mode: `Some(local_trust)` (the middleware inserts it on
//!   each request anyway; the default keeps construction uniform);
//! - daemon with auth **enforced**: `None`, so a missing request-extension
//!   `Principal` is an authentication error (fail closed) — never full
//!   access.
//!
//! T5: admins (and `local_trust`) see every store; `member` principals are
//! no longer rejected wholesale — instead the resolved store list is
//! filtered per call to just the `shared` stores they hold a grant for
//! (D7, D12), via `Principal::can_read_store`.
//!
//! specs/05-surfaces.md §3.1: a store name a tool call explicitly asks for
//! (`search`'s `stores` filter) that exists but was filtered out by D7 is a
//! `forbidden` tool error, not `store_not_found` — matching the HTTP surface
//! (`server::search_service::SearchService::query`'s `store_filter` handling)
//! exactly. Only a name absent from the *full*, pre-filter store list stays
//! `store_not_found`. With no store named explicitly (unfiltered `search`,
//! or `list_stores`), the visible set is silently narrowed as before — there
//! is nothing to be "forbidden" from since nothing specific was requested.

use std::sync::Arc;

use rmcp::{
    handler::server::{router::tool::ToolRouter, wrapper::Parameters},
    model::{CallToolResult, Extensions, Implementation, ServerCapabilities, ServerInfo},
    service::RequestContext,
    tool, tool_handler, tool_router, RoleServer, ServerHandler,
};

use localdb_core::{auth::Principal, types::StoreVisibility, Embedder, Error, StoreBackend};

use crate::args::{GetChunksArgs, GetDocumentArgs, ListDocumentsArgs, SearchArgs};
use crate::store_provider::StoreProvider;
use crate::tools::{self, AvailableStore};

/// Convert a `StoreProvider::available_stores` failure into a tool-level MCP
/// error result, so a broken/unavailable store backend surfaces as a normal
/// `CallToolResult { is_error: Some(true), .. }` rather than a panic — the
/// service itself stays up and can serve the next call.
fn provider_error(e: &Error) -> CallToolResult {
    tools::typed_error(e.code(), format!("failed to resolve available stores: {e}"))
}

/// Embedded-stdio / HTTP MCP server handler: holds a `StoreProvider` (stores
/// are resolved fresh on every tool call, not snapshotted at construction —
/// see `store_provider.rs`), the embedder used for `search`, whether
/// `--allow-write` was passed (parsed but always rejected in v1 — no
/// mutating tool is registered), and the fallback `Principal` for
/// transports that carry no per-request identity (see the module doc).
#[derive(Clone)]
pub struct McpHandler {
    pub backend: Arc<dyn StoreBackend>,
    pub provider: Arc<dyn StoreProvider>,
    pub embedder: Arc<dyn Embedder>,
    pub allow_write: bool,
    default_principal: Option<Principal>,
    tool_router: ToolRouter<Self>,
}

impl McpHandler {
    /// Create a new handler over the given store provider and embedder.
    ///
    /// `default_principal` is used when the request context carries no
    /// `Principal` (see the module doc): pass `Some(Principal::local_trust())`
    /// for embedded stdio and open-mode daemons, `None` when the daemon
    /// enforces auth so a missing principal fails closed.
    pub fn new(
        provider: Arc<dyn StoreProvider>,
        backend: Arc<dyn StoreBackend>,
        embedder: Arc<dyn Embedder>,
        allow_write: bool,
        default_principal: Option<Principal>,
    ) -> Self {
        Self {
            provider,
            backend,
            embedder,
            allow_write,
            default_principal,
            tool_router: Self::tool_router(),
        }
    }

    /// Resolve the caller's `Principal` for this tool call (R4).
    ///
    /// Takes the call's `rmcp::model::Extensions` (from
    /// `RequestContext.extensions`) rather than the whole context so the
    /// resolution path is unit-testable — `RequestContext` cannot be
    /// constructed outside rmcp (its `Peer::new` is `pub(crate)`), but
    /// `Extensions` can.
    ///
    /// Priority:
    /// 1. A `Principal` in the HTTP request extensions, reached through the
    ///    `http::request::Parts` rmcp injects into
    ///    `RequestContext.extensions` on the Streamable HTTP transport —
    ///    this is what the daemon's `require_auth` middleware inserted.
    /// 2. A `Principal` directly in the rmcp extensions (not produced by
    ///    any current transport; checked for completeness).
    /// 3. `self.default_principal` (embedded stdio / open mode).
    /// 4. Otherwise: fail closed with an `unauthorized` tool error — on an
    ///    enforced-auth daemon a missing extension means the auth layer was
    ///    bypassed, and answering with full access would be privilege
    ///    escalation.
    #[allow(clippy::result_large_err)] // CallToolResult follows the tool layer’s unboxed error convention.
    fn principal_for(&self, extensions: &Extensions) -> Result<Principal, CallToolResult> {
        if let Some(parts) = extensions.get::<http::request::Parts>() {
            if let Some(principal) = parts.extensions.get::<Principal>() {
                return Ok(principal.clone());
            }
        }
        if let Some(principal) = extensions.get::<Principal>() {
            return Ok(principal.clone());
        }
        match &self.default_principal {
            Some(principal) => Ok(principal.clone()),
            None => Err(tools::typed_error(
                "unauthorized",
                "no authenticated principal on this request; the MCP endpoint requires a \
                 valid bearer token",
            )),
        }
    }

    /// Resolve the current store list, or `None` (having already produced
    /// the tool-error result) on provider failure.
    #[allow(clippy::result_large_err)] // CallToolResult follows the tool layer’s unboxed error convention.
    async fn resolve_stores(&self) -> Result<Vec<AvailableStore>, CallToolResult> {
        self.provider
            .available_stores()
            .await
            .map_err(|e| provider_error(&e))
    }

    /// D7 filtering: keep only the stores `principal` may read. Admins (and
    /// `local_trust`) keep every store; members keep only `shared` stores
    /// they hold a grant for. An unrecognized visibility string (never
    /// produced by any current `StoreProvider`, so only reachable via a bug)
    /// is treated as `private` — fail safe, deny by default, rather than
    /// leak an unknown-shaped store to a member.
    fn filter_visible(principal: &Principal, stores: &[AvailableStore]) -> Vec<AvailableStore> {
        stores
            .iter()
            .filter(|s| {
                let visibility = StoreVisibility::parse(&s.descriptor.visibility)
                    .unwrap_or(StoreVisibility::Private);
                principal.can_read_store(&s.descriptor.name, visibility)
            })
            .cloned()
            .collect()
    }

    /// Shared per-tool preamble: resolve the caller's principal (fail closed
    /// if none — see `principal_for`), resolve the live store list, then
    /// filter it to what that principal may read (D7). Tools thus never see
    /// a store the caller isn't entitled to. For tools with no explicit
    /// store-name argument (`get_document`/`get_chunks`/`list_stores`) an
    /// invisible store behaves identically to an unknown one — there's
    /// nothing named to be "forbidden" from. `search`'s `stores` filter is
    /// the one call site with an explicit name, so it uses
    /// `authorize_and_resolve_with_full` instead (see below).
    #[allow(clippy::result_large_err)] // CallToolResult follows the tool layer’s unboxed error convention.
    async fn authorize_and_resolve(
        &self,
        extensions: &Extensions,
    ) -> Result<Vec<AvailableStore>, CallToolResult> {
        let principal = self.principal_for(extensions)?;
        let stores = self.resolve_stores().await?;
        Ok(Self::filter_visible(&principal, &stores))
    }

    /// Like `authorize_and_resolve`, but also returns the full, pre-D7-filter
    /// store list alongside the visible one — needed by `search_inner` to
    /// distinguish a named store that's unreadable (present in `full`,
    /// dropped from the visible set) from one that's genuinely unknown
    /// (absent from `full` too); see `forbidden_for_named_unreadable_store`.
    #[allow(clippy::result_large_err)] // CallToolResult follows the tool layer’s unboxed error convention.
    async fn authorize_and_resolve_with_full(
        &self,
        extensions: &Extensions,
    ) -> Result<(Vec<AvailableStore>, Vec<AvailableStore>), CallToolResult> {
        let principal = self.principal_for(extensions)?;
        let stores = self.resolve_stores().await?;
        let visible = Self::filter_visible(&principal, &stores);
        Ok((stores, visible))
    }

    /// Resolve names and IDs against the full registry before checking access.
    /// Reusing the tool resolver preserves ID precedence when a visible store's
    /// name collides with an unreadable store's ID.
    fn forbidden_for_named_unreadable_store(
        full: &[AvailableStore],
        visible: &[AvailableStore],
        requested: &[String],
    ) -> Option<CallToolResult> {
        if requested.is_empty() {
            return None;
        }
        let selected = match tools::select_mcp_stores(full, requested) {
            Ok(stores) => stores,
            Err(error) => return Some(error),
        };
        for store in selected {
            if !visible.iter().any(|s| s.descriptor.id == store.id) {
                return Some(tools::typed_error(
                    "forbidden",
                    format!("you do not have access to store '{}'", store.name),
                ));
            }
        }
        None
    }

    // The `*_inner` methods below carry the full tool behavior against a
    // bare `Extensions`; the `#[tool]` wrappers only peel it off the
    // `RequestContext`. Unit tests drive the inner methods directly
    // (`RequestContext` is not constructible outside rmcp); the
    // wrapper→inner hop plus rmcp's own extension propagation is covered by
    // the end-to-end test in `server/tests/` (R4).

    async fn search_inner(&self, args: SearchArgs, extensions: &Extensions) -> CallToolResult {
        let (full, visible) = match self.authorize_and_resolve_with_full(extensions).await {
            Ok(s) => s,
            Err(result) => return result,
        };
        if let Some(names) = &args.stores {
            if let Some(result) = Self::forbidden_for_named_unreadable_store(&full, &visible, names)
            {
                return result;
            }
        }
        tools::tool_search(&visible, self.embedder.as_ref(), args).await
    }

    async fn get_document_inner(
        &self,
        args: GetDocumentArgs,
        extensions: &Extensions,
    ) -> CallToolResult {
        let (full, stores) = match self.authorize_and_resolve_with_full(extensions).await {
            Ok(s) => s,
            Err(result) => return result,
        };
        if let Some(name) = &args.store {
            if let Some(error) = Self::forbidden_for_named_unreadable_store(
                &full,
                &stores,
                std::slice::from_ref(name),
            ) {
                return error;
            }
        }
        tools::tool_get_document(&stores, self.backend.as_ref(), args).await
    }

    async fn get_chunks_inner(
        &self,
        args: GetChunksArgs,
        extensions: &Extensions,
    ) -> CallToolResult {
        let (full, stores) = match self.authorize_and_resolve_with_full(extensions).await {
            Ok(s) => s,
            Err(result) => return result,
        };
        if let Some(name) = &args.store {
            if let Some(error) = Self::forbidden_for_named_unreadable_store(
                &full,
                &stores,
                std::slice::from_ref(name),
            ) {
                return error;
            }
        }
        tools::tool_get_chunks(&stores, args).await
    }

    async fn list_documents_inner(
        &self,
        args: ListDocumentsArgs,
        extensions: &Extensions,
    ) -> CallToolResult {
        let (full, stores) = match self.authorize_and_resolve_with_full(extensions).await {
            Ok(s) => s,
            Err(result) => return result,
        };
        if let Some(error) = Self::forbidden_for_named_unreadable_store(
            &full,
            &stores,
            std::slice::from_ref(&args.store),
        ) {
            return error;
        }
        tools::tool_list_documents(&stores, self.backend.as_ref(), args).await
    }

    async fn list_stores_inner(&self, extensions: &Extensions) -> CallToolResult {
        let stores = match self.authorize_and_resolve(extensions).await {
            Ok(s) => s,
            Err(result) => return result,
        };
        tools::tool_list_stores(&stores).await
    }
}

#[tool_router]
impl McpHandler {
    /// Hybrid search (BM25 + dense vector) across indexed stores. Returns a
    /// ranked list of citations in the canonical localdb Citation JSON shape.
    #[tool(
        description = "Hybrid search (BM25 + dense vector) across indexed stores. Returns a ranked list of citations in the canonical localdb Citation JSON shape."
    )]
    async fn search(
        &self,
        Parameters(args): Parameters<SearchArgs>,
        ctx: RequestContext<RoleServer>,
    ) -> CallToolResult {
        self.search_inner(args, &ctx.extensions).await
    }

    /// Fetch the normalized text and metadata for a document by its ID.
    #[tool(
        description = "Fetch the normalized text and metadata for a document by its ID or URI. Pass 'store' (id or name, e.g. from a search citation) to disambiguate when the same document id exists in multiple stores."
    )]
    async fn get_document(
        &self,
        Parameters(args): Parameters<GetDocumentArgs>,
        ctx: RequestContext<RoleServer>,
    ) -> CallToolResult {
        self.get_document_inner(args, &ctx.extensions).await
    }

    /// Fetch a document's chunks in order, paginated by offset/limit or by
    /// an anchor (anchor_chunk_id / anchor_block_seq) centered window.
    #[tool(
        description = "Fetch a document's chunks in order (block_seq, seq_in_block), paginated by offset/limit, or by an anchor_chunk_id/anchor_block_seq centered window (mutually exclusive with offset and with each other). Pass 'store' (id or name, e.g. from a search citation) to disambiguate when the same document id exists in multiple stores."
    )]
    async fn get_chunks(
        &self,
        Parameters(args): Parameters<GetChunksArgs>,
        ctx: RequestContext<RoleServer>,
    ) -> CallToolResult {
        self.get_chunks_inner(args, &ctx.extensions).await
    }

    /// List all available stores with their names, visibility, and
    /// document/chunk counts.
    #[tool(
        description = "List all available stores with their names, visibility, and document/chunk counts."
    )]
    async fn list_stores(&self, ctx: RequestContext<RoleServer>) -> CallToolResult {
        self.list_stores_inner(&ctx.extensions).await
    }
    #[tool(
        description = "List every document registered in a store (required 'store': id or name), optionally filtered by 'source' id, paginated by offset/limit (default 50, max 200)."
    )]
    async fn list_documents(
        &self,
        Parameters(args): Parameters<ListDocumentsArgs>,
        ctx: RequestContext<RoleServer>,
    ) -> CallToolResult {
        self.list_documents_inner(args, &ctx.extensions).await
    }
}

// `router = self.tool_router` reuses the stored instance field rather than
// rebuilding a fresh router via `Self::tool_router()` on every call (rmcp's
// default when no `router = ...` is given) — the field would otherwise be
// dead weight per rustc's dead-code lint, and reconstructing it per-call is
// wasted work for a routing table that never changes at runtime.
#[tool_handler(router = self.tool_router)]
impl ServerHandler for McpHandler {
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(ServerCapabilities::builder().enable_tools().build())
            .with_server_info(Implementation::new("localdb", env!("CARGO_PKG_VERSION")))
    }
}

#[cfg(test)]
mod tests;
