//! `McpHandler` — the `rmcp` `ServerHandler` implementation for localdb.
//!
//! Tool routing (`tools/list`, `tools/call`) is entirely macro-generated by
//! `#[tool_router]`/`#[tool_handler]`; there is no hand-written dispatch
//! table. Each `#[tool]` method here resolves the current store list via
//! `self.provider` (realtime — see `store_provider.rs`) and then forwards to
//! a `tools::*` fn — all validation and business logic lives in `tools.rs`,
//! which keeps its pure `&[AvailableStore]` signatures unchanged.

use std::sync::Arc;

use rmcp::{
    handler::server::{router::tool::ToolRouter, wrapper::Parameters},
    model::{CallToolResult, Implementation, ServerCapabilities, ServerInfo},
    tool, tool_handler, tool_router, ServerHandler,
};

use localdb_core::{Embedder, Error};

use crate::args::{GetChunksArgs, GetDocumentArgs, SearchArgs};
use crate::store_provider::StoreProvider;
use crate::tools::{self, AvailableStore};

/// Convert a `StoreProvider::available_stores` failure into a tool-level MCP
/// error result, so a broken/unavailable store backend surfaces as a normal
/// `CallToolResult { is_error: Some(true), .. }` rather than a panic — the
/// service itself stays up and can serve the next call.
fn provider_error(e: &Error) -> CallToolResult {
    tools::typed_error(e.code(), format!("failed to resolve available stores: {e}"))
}

/// Embedded-stdio / HTTP MCP server handler: holds a `StoreProvider` (stores
/// are resolved fresh on every tool call, not snapshotted at construction —
/// see `store_provider.rs`), the embedder used for `search`, and whether
/// `--allow-write` was passed (parsed but always rejected in v1 — no
/// mutating tool is registered).
#[derive(Clone)]
pub struct McpHandler {
    pub provider: Arc<dyn StoreProvider>,
    pub embedder: Arc<dyn Embedder>,
    pub allow_write: bool,
    tool_router: ToolRouter<Self>,
}

impl McpHandler {
    /// Create a new handler over the given store provider and embedder.
    pub fn new(
        provider: Arc<dyn StoreProvider>,
        embedder: Arc<dyn Embedder>,
        allow_write: bool,
    ) -> Self {
        Self {
            provider,
            embedder,
            allow_write,
            tool_router: Self::tool_router(),
        }
    }

    /// Resolve the current store list, or `None` (having already produced
    /// the tool-error result) on provider failure.
    async fn resolve_stores(&self) -> Result<Vec<AvailableStore>, CallToolResult> {
        self.provider
            .available_stores()
            .await
            .map_err(|e| provider_error(&e))
    }
}

#[tool_router]
impl McpHandler {
    /// Hybrid search (BM25 + dense vector) across indexed stores. Returns a
    /// ranked list of citations in the canonical localdb Citation JSON shape.
    #[tool(
        description = "Hybrid search (BM25 + dense vector) across indexed stores. Returns a ranked list of citations in the canonical localdb Citation JSON shape."
    )]
    async fn search(&self, Parameters(args): Parameters<SearchArgs>) -> CallToolResult {
        let stores = match self.resolve_stores().await {
            Ok(s) => s,
            Err(result) => return result,
        };
        tools::tool_search(&stores, self.embedder.as_ref(), args).await
    }

    /// Fetch the normalized text and metadata for a document by its ID.
    #[tool(description = "Fetch the normalized text and metadata for a document by its ID or URI.")]
    async fn get_document(&self, Parameters(args): Parameters<GetDocumentArgs>) -> CallToolResult {
        let stores = match self.resolve_stores().await {
            Ok(s) => s,
            Err(result) => return result,
        };
        tools::tool_get_document(&stores, args).await
    }

    /// Fetch a document's chunks in order, paginated by offset/limit.
    #[tool(
        description = "Fetch a document's chunks in order (block_seq, seq_in_block), paginated by offset/limit."
    )]
    async fn get_chunks(&self, Parameters(args): Parameters<GetChunksArgs>) -> CallToolResult {
        let stores = match self.resolve_stores().await {
            Ok(s) => s,
            Err(result) => return result,
        };
        tools::tool_get_chunks(&stores, args).await
    }

    /// List all available stores with their names, visibility, and
    /// document/chunk counts.
    #[tool(
        description = "List all available stores with their names, visibility, and document/chunk counts."
    )]
    async fn list_stores(&self) -> CallToolResult {
        let stores = match self.resolve_stores().await {
            Ok(s) => s,
            Err(result) => return result,
        };
        tools::tool_list_stores(&stores).await
    }
}

// `router = self.tool_router` reuses the stored instance field rather than
// rebuilding a fresh router via `Self::tool_router()` on every call (rmcp's
// default when no `router = ...` is given) — the field would otherwise be
// dead weight per rustc's dead-code lint, and reconstructing it per-call is
// wasted work for a routing table that never changes at runtime.
#[tool_handler(router = self.tool_router)]
impl ServerHandler for McpHandler {
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(ServerCapabilities::builder().enable_tools().build())
            .with_server_info(Implementation::new("localdb", env!("CARGO_PKG_VERSION")))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::store_provider::StaticStoreProvider;
    use async_trait::async_trait;
    use localdb_core::embedder::FakeEmbedder;

    /// A `StoreProvider` that always fails, to prove a provider error
    /// surfaces as a tool-level MCP error (not a panic) and the handler
    /// remains usable afterward.
    struct ErrorStoreProvider;

    #[async_trait]
    impl StoreProvider for ErrorStoreProvider {
        async fn available_stores(&self) -> Result<Vec<AvailableStore>, Error> {
            Err(Error::Internal {
                message: "backend unavailable".to_string(),
                correlation_id: "test_provider_error".to_string(),
            })
        }
    }

    fn embedder() -> Arc<dyn Embedder> {
        Arc::new(FakeEmbedder::new(4))
    }

    #[tokio::test]
    async fn list_stores_returns_tool_error_when_provider_fails() {
        let handler = McpHandler::new(Arc::new(ErrorStoreProvider), embedder(), false);
        let result = handler.list_stores().await;
        assert_eq!(result.is_error, Some(true));
        let text = result.content[0].as_text().unwrap().text.clone();
        let parsed: serde_json::Value = serde_json::from_str(&text).expect("must be JSON");
        assert_eq!(parsed["error"]["code"].as_str().unwrap(), "internal");
        assert!(parsed["error"]["message"]
            .as_str()
            .unwrap()
            .contains("backend unavailable"));
    }

    #[tokio::test]
    async fn handler_stays_usable_after_a_provider_error() {
        let handler = McpHandler::new(Arc::new(ErrorStoreProvider), embedder(), false);

        let first = handler.list_stores().await;
        assert_eq!(first.is_error, Some(true));

        // The service must not have panicked or otherwise become unusable —
        // a second call against the same (still-failing) provider still
        // produces a clean tool-level error, not a crash.
        let second = handler.list_stores().await;
        assert_eq!(second.is_error, Some(true));
    }

    #[tokio::test]
    async fn list_stores_succeeds_once_provider_recovers() {
        // Same handler *shape* as the static case — proves a working
        // provider still round-trips normally through `resolve_stores`.
        let provider = Arc::new(StaticStoreProvider::new(vec![]));
        let handler = McpHandler::new(provider, embedder(), false);
        let result = handler.list_stores().await;
        assert_ne!(result.is_error, Some(true));
    }
}
